### ISSUE TITLE
Bug in codebase

### ISSUE THREAD

**Issue by niftylettuce** [ejhayes/passport-otp#1]
https://github.com/ejhayes/passport-otp/blob/70f56fabef54d3f76a9b85171effc9718d67bffa/lib/strategy.js#L57

This isn't really a valid JavaScript line of code

**Comment by ejhayes** [comment]
Well that's just embarrassing. I'll fix. Thanks for pointing out @niftylettuce .

**Comment by Climax777** [comment]
@ejhayes could you please consider the merge request?

**Comment by shaunwarman** [comment]
Can https://github.com/ejhayes/passport-otp/pull/2 be merged, doesn't look like my `window` option is being honored.

**Comment by niftylettuce** [comment]
I've published `@ladjs/passport-otp-strategy@1.1.0` in the interim until this is fixed.  Also the code is available as a fork of @Climax777 at https://github.com/ladjs/passport-otp

**Comment by niftylettuce** [comment]
please release a new version to npm @ejhayes

**Comment by ejhayes** [comment]
:rocket: Issue was released in [`v1.2.0`](https://github.com/ejhayes/passport-otp/releases/tag/v1.2.0) :rocket:

**Comment by ejhayes** [comment]
:rocket: Issue was released in [`v1.2.0`](https://github.com/ejhayes/passport-otp/releases/tag/v1.2.0) :rocket:
